### ISSUE TITLE
cmake failed, I had the cplex/HDF5 installed

### ISSUE THREAD

**Issue by andyyuan78** [opengm/opengm#371]
ubgpu@ubgpu:~/github/opengm/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- --------------------------------------------------------------------------
-- WARNING: Compiler warnings are very sloppy -> increase CMake-WARNINGLEVEL
-- --------------------------------------------------------------------------
-- build without CPLEX interface
-- build without AD3 interface
-- build without GUROBI interface
-- build without Boost
-- build without HDF5
-- build without external inference algorithm TRWS
-- build without external inference algorithm GCO
-- build without external inference algorithm MRF
-- build without external inference algorithm QPBO
-- build without external inference algorithm FastPD
-- build without external inference algorithm MaxFlow-IBFS
-- build without external inference algorithm MaxFlow
-- build without VIGRA
-- build without inference algorithm DDBundle
-- build without external inference library grante
-- build without openMP -> multithreaded options disabled
-- build without external inference algorithms from  LibDai
-- build without external inference algorithm DAOOPT
-- build without external inference algorithm MPLP
-- build without external inference algorithm MPLP
-- build without external inference algorithm PLANARYTY
-- build without external inference algorithm BLOSSOM5
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Linking to RT is enabled
Constrained Graphical Models Examples require Cplex or Gurobi
-- Found VIGRA: /usr/local/lib/libvigraimpex.so  
CMake Error at src/tutorials/c++/applications/CMakeLists.txt:34 (message):
  mrf-benchmark can only be built with HDF5.  set WITH_HDF5 to build to HDF5.

-- Configuring incomplete, errors occurred!
See also "/home/ubgpu/github/opengm/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubgpu/github/opengm/build/CMakeFiles/CMakeError.log".
ubgpu@ubgpu:~/github/opengm/build$

**Comment by joergkappes** [comment]
If U set the flag for WITH_HDF5 in cmake it will work.

But I will fix the cmake script, too, since it should skip the tutorial if U build without HDF5

**Comment by andyyuan78** [comment]
how to do that?

BTW, how to start GUI to install?

**Comment by joergkappes** [comment]
I have fixed the cmake file. 
"git pull" should fix your problem.
