### ISSUE TITLE
how to install from git clone ?

### ISSUE THREAD

**Issue by andyyuan78** [opengm/opengm#373]
By opengm-2.0.2-beta-manual.pdf, we just need run a GUI or 

make /make test/ make externalLibs

but it don't work.

**Comment by joergkappes** [comment]
Without a more detailed description of "don't work" no one will be able to help You.

Best
Joerg

**Comment by andyyuan78** [comment]
the make are passed,

but not know how to start the installation GUI.

**Comment by joergkappes** [comment]
Which installation GUI ???

Did You mean the cmake-gui? If so You should have a look at a cmake-tutorial.
OpenGM itself have only a shell installation script.

**Comment by andyyuan78** [comment]
thanks.
this is the first time I use cmake-gui.
