### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by ghisvail** [opengm/opengm#380]
Please consider pushing tags for the current and future stable releases of OpenGM.

**Comment by ghisvail** [comment]
Actually, the [CMake version metadata](https://github.com/opengm/opengm/blob/master/CMakeLists.txt) shows `2.3.1`, whilst the [changelog](https://github.com/opengm/opengm/blob/master/ChangeLog.txt) mentions `2.3.5`.

**Comment by ghisvail** [comment]
I have managed to successfully build a Debian package for OpenGM that I intend to submit for inclusion to the Debian archive, if you are happy with this idea. I needed a tag for the latest stable version, hence myself filing this issue.

Based on the history, I tagged commit 76e8a78b52d41e934d40c5f4f8daa0e8f7b2a900 as `v2.3.5`. Please let me know whether this is correct. FYI, it does not matter whether the current snapshot of `master` is tagged, only that at least one tag exists within the complete history.

Thanks,

**Comment by joergkappes** [comment]
Hi Ghislain,
the commit 76e8a78b52d41e934d40c5f4f8daa0e8f7b2a900 is equivalent to 'v2.3.5'.
I will release the version 'v2.3.6' when I hopefully will find some time during the next week.
This time I try to not forget to add a tag - I promise.

I am curious to the Debian package for OpenGM. Does this includes only the core library or also the external libraries?

Best
Joerg

**Comment by joergkappes** [comment]
I have pushed the tag for version 2.3.5.

Best Joerg

**Comment by ghisvail** [comment]
> I have pushed the tag for version 2.3.5.

Good thanks.

> I am curious to the Debian package for OpenGM. Does this includes only the core library or also the external libraries?

For now only the core built with BOOST, HDF5, and VIGRA enabled. Debian's policy is to avoid shipping embedded dependencies, so external libraries (GCO, QBPO...) would have to be packaged first before being enabled in the Debian packaged OpenGM later.

Also, I was able to build everything (library, api doc, python module, python doc, cli and converters), but it required a little bit of patching from the original sources. If you're happy with it, I would like to forward some of these patches to you in form of PRs so they are included in the next release.

**Comment by joergkappes** [comment]
Any improvements are welcome. Just send your PRs and I will have a look.
