### ISSUE TITLE
Use of non-free licensed Lena image

### ISSUE THREAD

**Issue by ghisvail** [opengm/opengm#389]
Although redistributable, the Lena image shipped under `src/interfaces/python/examples/lena.bmp` is [not freely licensed](https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html).

Please consider removing it if it is not essential to any components of the package, or use a more suitably licensed image.

**Comment by joergkappes** [comment]
Replaced by a free Lena image with #3c1680845b7dd1516c606c00946d2fb90b1740e5 ;-)

**Comment by ghisvail** [comment]
The Lena file is still in the tree:
https://github.com/opengm/opengm/blob/master/src/interfaces/python/examples/lena.bmp
