### ISSUE TITLE
Provide citation and or bibtex reference for OpenGM

### ISSUE THREAD

**Issue by ghisvail** [opengm/opengm#395]
If they are available, please provide a citation string and / or bibtex reference for OpenGM. You may paste it here or insert it somewhere in the README file at your convenience. That way I can update the packaging metadata with the right information about the software and help you getting appropriate credit from future users of the Debian package.

I take this opportunity to thank you for merging all my proposed changes. These make for a much more packaging friendly installation process.

**Comment by joergkappes** [comment]
Added to Readme.md with #0c423445d247d60766ca343d84f41448b0b0dc92

**Comment by ghisvail** [comment]
Awesome. With this done, as far as packaging goes, I believe everything is in place. How far off are you for the next release?

**Comment by joergkappes** [comment]
When there will be no more PRs from You I will go for the next release end of the week.

**Comment by ghisvail** [comment]
@joergkappes 
I don't have anymore issues to file. Everything looks good on the packaging side. Feel free to publish the new release whenever your like.

Many thanks for your cooperation.
