### ISSUE TITLE
GraphicalModel::addVariable uses size_t instead of IndexType

### ISSUE THREAD

**Issue by schuhschuh** [opengm/opengm#417]
[Here](https://github.com/opengm/opengm/blob/d1946b5fc60ba032fdb0e15a0fe657bd6e47df3d/include/opengm/graphicalmodel/graphicalmodel.hxx#L377), ```IndexType``` should be used instead of ```size_t```. Cannot use ```GraphicalModel::addVariable``` when my IndexType and LabelType is ```int``` instead. 
Also, there is generally a mismatch between the argument types of the graphical model space functions and the graphical model functions. The type of the ```GraphicalModel::addVariable``` argument is ```IndexType```, but in case of ```DiscreteSpace::addVariable``` it is ```LabelType```. Both are usually identical, but the existence of different space template parameters should not require them to be identical.

**Comment by joergkappes** [comment]
fixed. Thanks for pointing this out.
