### ISSUE TITLE
opengm master state

### ISSUE THREAD

**Issue by DerThorsten** [opengm/opengm#433]
Hi @chaubold   @joergkappes,

I think both of you are  unhappy with the current master of opengm.
Carsten might want  learning back in the master, joerg wants a hard reset
to the point before learning was in the master in the first place, and the re-adding the new changes.

I really do not like the hard rest.  I have the feeling this could lead to some more trouble.
Iff we agree on the hard reset which commit do we pick?

sorry for the inconvenience.

**Comment by joergkappes** [comment]
Hi,
I think the learning-experimental branch is not ready to be merged into the master. I do not see a problem for Carsten to use the learning branch if he needs these features.
However, we should keep this to branches as compatible as possible. With this merge and remove actions I feel that there are no longer compatible, e.g. try to fix a bug in the master an push this into the experimental branch - good luck!

If You have a look at the graph

https://github.com/opengm/opengm/network

I would suggest to roll back to #419 and commit the view changes again.
To be on the save side one should keep a full copy checked out as backup.

Jörg

**Comment by chaubold** [comment]
Hey guys,

I know that the learning branch is far from being fully tested etc. I was actually wondering why you've merged it into master. But once it was in, this resolved some problems for me: When we're going to add the structured learning version of tracking to the next ilastik release we could then have used the same opengm version everywhere. But because from the C++ side we just need the headers, we can probably compile the tracking stuff against opengm-learning and use opengm-master everywhere else.

Rolling back to a certain commit sounds like an ugly option that requires a git force-push. @DerThorsten suggested he'd rather remove the files in question by hand (as git reverting a merge commit does not work).

**Comment by svenpeter42** [comment]
git revert -m 1 merge commit (or -m 2 if you want to revert to the "other" mainline) usually does a good job if you want to revert a full merge.

in this case
```
% git revert -m 1 f8f448c0b5009882b6dbf8ab34df41711b72b0e9                                                                                                                                                                                                 :(
error: could not revert f8f448c... Merge pull request #423 from opengm/learning-experimental
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
% git status                                                                                                                                                                                                                                               :(
On branch master
Your branch is up-to-date with 'origin/master'.
You are currently reverting commit f8f448c.
  (fix conflicts and run "git revert --continue")
  (use "git revert --abort" to cancel the revert operation)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   .gitignore
	modified:   CMakeLists.txt
	modified:   README.md
	deleted:    fubar/brown_horse.py
	deleted:    fubar/brown_horse2.py
	deleted:    fubar/brown_horse_sp.py
	deleted:    fubar/example1.py
	deleted:    fubar/make_grid_potts_dset.py
	deleted:    fubar/make_mc_dset.py
	deleted:    fubar/max_likelihood_example.py
	deleted:    fubar/noisy_squares_3_labels.py
	deleted:    fubar/pascal_voc/convertPascalVOC.py
	deleted:    fubar/pascal_voc/convertPascalVOCNew.py
	deleted:    fubar/pascal_voc/learnPascalVOC.py
	deleted:    fubar/python_stuff.py
	deleted:    fubar/real_example.py
	deleted:    fubar/real_example_2.py
	deleted:    fubar/simple_sp.py
	deleted:    fubar/toy_dataset.py
	deleted:    fubar/whorse.py
	modified:   include/opengm/datastructures/marray/marray_hdf5.hxx
	modified:   include/opengm/functions/function_properties_base.hxx
	new file:   include/opengm/functions/l_potts.hxx
	modified:   include/opengm/functions/potts.hxx
	modified:   include/opengm/functions/readme.txt
	deleted:    include/opengm/functions/unary_loss_function.hxx
	modified:   include/opengm/functions/view_convert_function.hxx
	modified:   include/opengm/graphicalmodel/graphicalmodel.hxx
	modified:   include/opengm/graphicalmodel/graphicalmodel_factor.hxx
	modified:   include/opengm/graphicalmodel/graphicalmodel_function_wrapper.hxx
	new file:   include/opengm/graphicalmodel/parameters.hxx
	deleted:    include/opengm/graphicalmodel/weights.hxx
	modified:   include/opengm/inference/alphabetaswap.hxx
	modified:   include/opengm/inference/alphaexpansion.hxx
	modified:   include/opengm/inference/alphaexpansionfusion.hxx
	modified:   include/opengm/inference/astar.hxx
	modified:   include/opengm/inference/auxiliary/fusion_move/fusion_mover.hxx
	modified:   include/opengm/inference/auxiliary/lp_solver/lp_solver_interface.hxx
	modified:   include/opengm/inference/bruteforce.hxx
	modified:   include/opengm/inference/combilp.hxx
	modified:   include/opengm/inference/dualdecomposition/dualdecomposition_bundle.hxx
	modified:   include/opengm/inference/dualdecomposition/dualdecomposition_subgradient.hxx
	modified:   include/opengm/inference/dynamicprogramming.hxx
	modified:   include/opengm/inference/external/ad3.hxx
	modified:   include/opengm/inference/external/daoopt.hxx
	modified:   include/opengm/inference/external/fastPD.hxx
	modified:   include/opengm/inference/external/mrflib.hxx
	modified:   include/opengm/inference/external/qpbo.hxx
	modified:   include/opengm/inference/external/trws.hxx
	modified:   include/opengm/inference/fusion_based_inf.hxx
	modified:   include/opengm/inference/graphcut.hxx
	modified:   include/opengm/inference/greedygremlin.hxx
	modified:   include/opengm/inference/hqpbo.hxx
	modified:   include/opengm/inference/icm.hxx
	modified:   include/opengm/inference/infandflip.hxx
	modified:   include/opengm/inference/inference.hxx
	modified:   include/opengm/inference/lazyflipper.hxx
	modified:   include/opengm/inference/loc.hxx
	modified:   include/opengm/inference/lp_inference_base.hxx
	modified:   include/opengm/inference/lpcplex.hxx
	modified:   include/opengm/inference/lpcplex2.hxx
	modified:   include/opengm/inference/lpgurobi.hxx
	modified:   include/opengm/inference/lpgurobi2.hxx
	modified:   include/opengm/inference/lsatr.hxx
	modified:   include/opengm/inference/messagepassing/messagepassing.hxx
	modified:   include/opengm/inference/messagepassing/messagepassing_bp.hxx
	modified:   include/opengm/inference/messagepassing/messagepassing_trbp.hxx
	modified:   include/opengm/inference/movemaker.hxx
	modified:   include/opengm/inference/mqpbo.hxx
	modified:   include/opengm/inference/multicut.hxx
	modified:   include/opengm/inference/partition-move.hxx
	modified:   include/opengm/inference/qpbo.hxx
	modified:   include/opengm/inference/reducedinference.hxx
	modified:   include/opengm/inference/sat.hxx
	modified:   include/opengm/inference/self_fusion.hxx
	modified:   include/opengm/python/numpyview.hxx
	modified:   include/opengm/utilities/metaprogramming.hxx
	modified:   include/opengm/utilities/shape_accessor.hxx
	modified:   src/examples/unsorted-examples/inference_types.cxx
	modified:   src/interfaces/commandline/double/opengm_min_sum.cxx
	modified:   src/interfaces/python/opengm/__init__.py
	modified:   src/interfaces/python/opengm/_inference_interface_generator.py
	modified:   src/interfaces/python/opengm/functionhelper.py
	modified:   src/interfaces/python/opengm/inference/inf_def_visitor.hxx
	modified:   src/interfaces/python/opengm/inference/pyFusionMoves.cxx
	modified:   src/interfaces/python/opengm/opengmcore/__init__.py
	modified:   src/interfaces/python/opengm/opengmcore/function_injector.py
	modified:   src/interfaces/python/opengm/opengmcore/opengmcore.cpp
	modified:   src/interfaces/python/opengm/opengmcore/pyFunctionGen.cxx
	modified:   src/interfaces/python/test.py
	modified:   src/tutorials/c++/basics/doMinSumInference.cxx
	modified:   src/tutorials/c++/basics/doSumProdInference.cxx
	modified:   src/unittest/inference/test_graphcut.cxx
	modified:   src/unittest/inference/test_lazyflipper.cxx
	modified:   src/unittest/inference/test_messagepassing.cxx
	modified:   src/unittest/test_gm_learning_functions.cxx
	modified:   src/unittest/test_linear_constraint.cxx

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   .travis.yml
	both modified:   include/opengm/python/opengmpython.hxx
	both modified:   src/interfaces/python/opengm/CMakeLists.txt
	both modified:   src/interfaces/python/opengm/opengmcore/pyFunctionTypes.cxx
	both modified:   src/interfaces/python/opengm/opengmcore/pyGm.cxx
	both modified:   src/unittest/CMakeLists.txt

```

and the conflicts don't look too bad. Then in the learning-experimental just revert the revert and continue as usual.

**Comment by ghisvail** [comment]
Please do not force-push as the Debian packaging repository is sync'd with this one.

**Comment by joergkappes** [comment]
@svenpeter42 I am not sure if "git revert" really solves the problem. It adds just more commits such that the code is consistent to the older version. However what happen if You make a PR from the master to the branch learning-experimental, which has been merged to master and then "removed" by a sequence of commits. What do You think?

@ghisvail The master is currently broken, we will add no more PR if this problem is not solved.

Would it be a option to build a branch before the bad PR and then rename the branches?
master -> master-obsolete
new-branch -> master

**Comment by svenpeter42** [comment]
First revert all of Thorsten's manual deletions in master, then revert the
merge.
Switch to learning, cherry pick Thorsten's commits, the commit that reverts
those and the commit that reverts the merge. Then issue another revert for
the revert of the merge.

No need to force push anything and merges between branches will work just
fine. I can do this later in a fork if I find some time  so that you can
check for yourself ;)

**Comment by ghisvail** [comment]
> The master is currently broken, we will add no more PR if this problem is not solved.

Understood.

> Would it be a option to build a branch before the bad PR and then rename the branches?

There needs to be continuity in the history in the `master` branch history. The solution you propose would break this. What @svenpeter42 proposes sounds much more sensible.

**Comment by svenpeter42** [comment]
i'm not familiar enough with the code base to ensure that what i did here is correct - please check carefully.
i just merged master into learning-experimental since that was less trouble than cherry-picking individual commits.

**Comment by joergkappes** [comment]
I feel that it is better to branch before the silly learning merge and continue with this clean branch.  
The current master is then marked as obsolete.
Optionally one can rename the branches that the new master is then called master again.

All commits that have been merged in the broken master have to be included in the new clean master.
I think this is the saver way and easier to understand afterwards.

**Comment by ghisvail** [comment]
This would break all forks of the repository (including the one used for packaging) and require manual intervention to get the individual forks syn'c again with upstream. This is bad.

If you guys really want to go the "lazy" way, then consider staging the proposed "fixed master" branch separately, checkout `master`, delete all files, add the content of `fixed master` manually, and finally commit. Git will then figure it out from here and you'll keep the continuity of the `master` branch.

Please don't break `master`.

**Comment by chaubold** [comment]
I agree, just discontinuing the current `master` branch is not a viable option. @joergkappes did you look at @svenpeter42's PRs? Don't they achieve what we need?

**Comment by svenpeter42** [comment]
@ghisvail's proposal should be identical to what my PRs do. Don't forget to
cherry pick Thorsten's manual reverts and revert those and the "deleted
everything and added back sane copy" commit in learning-experimental if you
want merges to work as expected.

**Comment by joergkappes** [comment]
@svenpeter42 the problem with your PRs is that You revert a HUGE PRs with a HUGE PRs. Finally, no one knows what is going on when looking on it. It is more than touching a view files. I am not willing to take care to check if this is correct, do someone else?

@ghisvail I have reject this stupid PRs to the master before it was accepted (not by me) and I am looking for an easy and _clean_ way to resolve this, such that I can guarantee that nothing gets broken. If no one else feel responsible and verify correctness, I will do it the LAZY way even if this means that all forks have to be synced manually.

**Comment by svenpeter42** [comment]
Calling things stupid and asserting blame isn't going to solve this issue.
And force pushing or renaming master is the very opposite of clean.

The requests just look huge because github's UI is misleading at best. I
can show you tomorrow with the CLI that the pull requests are actually
remarkably small (just git diff between the last sane state in master and
the state after my PR would be applied. The only difference should be the
new changes after the merge)
The only thing you need to verify manually is that the PR to learning
experimental only includes the changes done to master after the merge.

**Comment by joergkappes** [comment]
Sorry for my last unconstructive comment.
But I am a bit annoyed that there are still changes in the master branch even this issue is not solved and after all of this, there are still ingoing PRs from experimental learning branches to the master-branch. *arg*

Give me some time to cool done ;-)

I got all the points and will think about it again ...

**Comment by joergkappes** [comment]
I finally take the time for comparing the older stable versions with the one of Sven.
Ignoring the changes in between, the overall change was indeed small in both branches, so I go this way.

Both branches should be clean now.

Please check if it compiles for You. 
Before we continue merging other PRs, we should try to get travis work again. 

Maybe I can have a look tomorrow.

**Comment by ghisvail** [comment]
Since development activity has resumed on `master`, I am assuming this is now fixed right?

Could you guys let me know of the next commit id I should test / provide for the Debian packaging. Right now, we have the same version as the tagged `2.3.7RC`.

Thanks.

**Comment by joergkappes** [comment]
I have fixed the most problems.
For travis the installation of some python or boost libs on OSX does not work yet, that why I can not test the Python building there. I would like to fix this before I go on with the PRs concerning Python.

The opengm-website is also available due its old URL.

So this issue is solved
