### ISSUE TITLE
Memory leak in FastSequence

### ISSUE THREAD

**Issue by bluescarni** [opengm/opengm#437]
clang's address sanitizer reports a memory leak in ``FastSequence``. The problem seems to be in the destructor:

```c++
template<class T, size_t MAX_STACK>
FastSequence<T, MAX_STACK>::~FastSequence( ) {
   if(size_>MAX_STACK) {
      OPENGM_ASSERT(pointerToSequence_!=NULL);
      delete[] pointerToSequence_;
   }
}
```
I think the check should be ``capacity_>MAX_STACK`` rather than ``size_>MAX_STACK``. As far as I have understood, capacity can only increase over the lifetime of the object, but the size can also decrease. So there could be a situation in which the size is small but the capacity is big enough to have resulted in dynamic allocation (and thus requiring the ``delete`` operation on the dynamic array).

#436 contains the change. No memory leaks are reported any more.

**Comment by DerThorsten** [comment]
nice work!
