### ISSUE TITLE
Memory access error in test_partitions.cxx

### ISSUE THREAD

**Issue by bluescarni** [opengm/opengm#439]
clang's address sanitizer reports that the following statement results in an out-of-bounds memory access in ``test_partitions.cxx``:

```c++
OPENGM_TEST(P.getPartition(5)>8);
```
@DerThorsten mentioned that it is probably better to just comment out the offending line.
 This is done in #438.

**Comment by DerThorsten** [comment]
@joergkappes  you might want to have a closer look

**Comment by joergkappes** [comment]
This is definitely a bug.
I think when I wrote this test, I had another interface in mind as I implement.

Either remove this line or getPartition should return size_t::max when out of partition range.
