### ISSUE TITLE
FTBFS on FreeBSD and Hurd kernels

### ISSUE THREAD

**Issue by ghisvail** [opengm/opengm#445]
The [current package](https://buildd.debian.org/status/package.php?p=opengm) (same as the 2.3.7RC tag) on Debian fails to build on alternative kernels such as GNU/kFreeBSD (kfreebsd-i386 and kfreebsd-amd64) and GNU/Hurd (hurd-i386).

The build on these architectures fails early with the following error:
```
In file included from /«BUILDDIR»/opengm-2.3.6+20160131/include/opengm/inference/visitors/visitors.hxx:9:0,
                 from /«BUILDDIR»/opengm-2.3.6+20160131/include/opengm/inference/messagepassing/messagepassing.hxx:18,
                 from /«BUILDDIR»/opengm-2.3.6+20160131/src/examples/image-processing-examples/grid_potts.cxx:5:
/«BUILDDIR»/opengm-2.3.6+20160131/include/opengm/utilities/meminfo.hxx: In static member function 'static double sys::MemoryInfo::usedSystemMem()':
/«BUILDDIR»/opengm-2.3.6+20160131/include/opengm/utilities/meminfo.hxx:135:22: error: aggregate 'sys::MemoryInfo::usedSystemMem()::sysinfo memInfo' has incomplete type and cannot be defined
       struct sysinfo memInfo;
                      ^
/«BUILDDIR»/opengm-2.3.6+20160131/include/opengm/utilities/meminfo.hxx: In static member function 'static double sys::MemoryInfo::freeSystemMem()':
/«BUILDDIR»/opengm-2.3.6+20160131/include/opengm/utilities/meminfo.hxx:140:22: error: aggregate 'sys::MemoryInfo::freeSystemMem()::sysinfo memInfo' has incomplete type and cannot be defined
       struct sysinfo memInfo;
                      ^
/«BUILDDIR»/opengm-2.3.6+20160131/include/opengm/utilities/meminfo.hxx: In static member function 'static double sys::MemoryInfo::systemMem()':
/«BUILDDIR»/opengm-2.3.6+20160131/include/opengm/utilities/meminfo.hxx:145:22: error: aggregate 'sys::MemoryInfo::systemMem()::sysinfo memInfo' has incomplete type and cannot be defined
       struct sysinfo memInfo;
``` 
But looking at the content of `include/opengm/utilities/meminfo.hxx`, I fail to see which path the compiler is taking that leads to an incomplete type definition.

Any ideas?

**Comment by joergkappes** [comment]
Hotfix: Comment out #define SYS_MEMORYINFO_ON

this should be only activated when it is realy needed. It is only used in 
the visitor to logging the memory requirements of infernce methods, which 
was requested by reviewers ;-)

Maybe I can fix this later -it is not a big think. I just have to move the 
option for the define to cmake.

Jörg

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 1. April 2016 18:21:53 schrieb Ghislain Antony Vaillant 
<notifications@github.com>:

**Comment by ghisvail** [comment]
I'll try the suggested hotfix. Thanks Joerg.

**Comment by joergkappes** [comment]
should be fixed, test is disabled by default, too

**Comment by ghisvail** [comment]
Just to confirm that your commit fixed the build of the affected architectures. Thanks.
