### ISSUE TITLE
visualizeGm not working with new version of Python Networkx library

### ISSUE THREAD

**Issue by shaunirwin** [opengm/opengm#453]
Calling opengm.visualizeGM() fails with the latest version of networkx (i.e. version 1.11).  It fails on the following line of opengm/src/interfaces/python/opengm/_visu.py:

`from networkx import graphviz_layout`

The error message:

> Traceback (most recent call last):
>   File "/home/shaun/My_Projects/opengm_tests_2/plot_graph.py", line 18, in <module>
>     plotNonShared=True,relNodeSize=0.4)
>   File "/home/shaun/My_Projects/opengm_tests_2/opengm/_visu.py", line 45, in visualizeGm
>     raise TypeError("\"from networkx import graphviz_layout\" failed")  
> TypeError: "from networkx import graphviz_layout" failed

[This](http://stackoverflow.com/questions/35279733/what-could-cause-networkx-pygraphviz-to-work-fine-alone-but-not-together) post on StackOverflow explains the issue. My temporary solution was to downgrade networkx to version 1.10, although it would be best to make it compatible with the new version too.

**Comment by Erotemic** [comment]
Another way to work around this on the opengm user side is to do: 

``` 
import networkx 
from networkx.drawing.nx_agraph import graphviz_layout
networkx.graphviz_layout = graphviz_layout
```

This causes `from networkx import graphviz_layout` to work
