### ISSUE TITLE
Missing declaration of `libpython` in cmake file used to build python interface.

### ISSUE THREAD

**Issue by se4u** [opengm/opengm#463]
The section on Link Libraries in file `src/interfaces/python/opengm/opengmcore/CMakeLists.txt` misses out on linking the `PYTHON_LIBRARIES`. Consequently the python wrapper does not build. The following change can fix this problem.

    #--------------------------------------------------------------
    # Link libraries
    #--------------------------------------------------------------
    + target_link_libraries(_opengmcore ${PYTHON_LIBRARIES})

This problem can be reproduced by changing the top level `CMakeLists` and then building

    OPTION(BUILD_PYTHON_WRAPPER "Build python wrapper" ON)

Assuming that the boost python libraries dont statically link the python libraries themselves.

**Comment by se4u** [comment]
This same fix needs to be done in `interfaces/python/opengm/inference/CMakeLists.txt` and `interfaces/python/opengm/hdf5/CMakeLists.txt`

**Comment by yunesj** [comment]
I have a pull request that includes this change.

https://github.com/opengm/opengm/pull/460/commits/bd823bf949dc724d26b397b12cb8c1aa656ba89a
