### ISSUE TITLE
FTBFS on i386: request for member X which is of non-class type 'const long long unsigned int'

### ISSUE THREAD

**Issue by ghisvail** [opengm/opengm#475]
The current tip of `master` fails to build from source on `i386` (but fine on `amd64`) due to the following errors:
```
/<<BUILDDIR>>/opengm-2.3.6+20160814/include/opengm/inference/lazyflipper.hxx:169:29: error: request for member 'maxSubgraphSize_' in 'p', which is of non-class type 'const long long unsigned int'
       :  maxSubgraphSize_(p.maxSubgraphSize_),
                           ~~^~~~~~~~~~~~~~~~
/<<BUILDDIR>>/opengm-2.3.6+20160814/include/opengm/inference/lazyflipper.hxx:170:27: error: request for member 'startingPoint_' in 'p', which is of non-class type 'const long long unsigned int'
          startingPoint_(p.startingPoint_),
                         ~~^~~~~~~~~~~~~~
/<<BUILDDIR>>/opengm-2.3.6+20160814/include/opengm/inference/lazyflipper.hxx:171:29: error: request for member 'inferMultilabel_' in 'p', which is of non-class type 'const long long unsigned int'
          inferMultilabel_(p.inferMultilabel_)
```
The detailed build log is available [here](http://debomatic-i386.debian.net/distribution#unstable/opengm/2.3.6+20160814-1/buildlog).

**Comment by ghisvail** [comment]
Quick update to confirm the failure is happening for all 32-bit architectures, see [here](https://buildd.debian.org/status/logs.php?pkg=opengm&ver=2.3.6%2B20160814-1)

**Comment by ghisvail** [comment]
And the corresponding bug report [downstream](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836216).

**Comment by joergkappes** [comment]
I will have a look. Should not be a big thing.
During merging I run test on 64bit only. That's why I miss this.

**Comment by ghisvail** [comment]
I am currently testing the packaging with the new tip of `master` and will report if other things come up.

**Comment by ghisvail** [comment]
The FTBFS is fixed. Thanks @joergkappes. Closing.
