### ISSUE TITLE
FTBFS on powerpc: test-io-hdf5 data types not equal

### ISSUE THREAD

**Issue by ghisvail** [opengm/opengm#477]
[Forwarded](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836413) from the Debian bug tracker.

Looks like the `test-io-hdf5` if failing for selected architectures (including `mips`, `powerpc` and `s390x`) with the following error:
```
23/49 Test #24: test-io-hdf5 .....................***Exception: Other  0.11 sec
terminate called after throwing an instance of 'std::runtime_error'
  what():  Data types not equal error.
```

Any idea where this could come from?

Cheers,
Ghis

**Comment by ghisvail** [comment]
Build logs: https://buildd.debian.org/status/logs.php?pkg=opengm&ver=2.3.6%2B20160901-1

**Comment by joergkappes** [comment]
I figure out the problem, it little and big endian.
marray maps float and double to little endian.

I will have a look how to fix this.

**Comment by ghisvail** [comment]
Nice, let me know when you have a fix.

**Comment by joergkappes** [comment]
Should be fixed, but I have no system to test it.

**Comment by ghisvail** [comment]
I should be able to test it. Will report in case other problems show up. Thanks for looking it up.

**Comment by ghisvail** [comment]
All good. Many thanks for the prompt fixing. Closing.
