### ISSUE TITLE
cast problem

### ISSUE THREAD

**Issue by ReinhardHameeteman** [opengm/opengm#483]
Correct me if I am wrong, but it seems to me that line 546 of 
https://github.com/opengm/opengm/blob/master/include/opengm/inference/trws/trws_subproblemsolver.hxx
should read
IndexType v[2];
in stead of 
LabelType v[2];

On line 550
_masterModel[pwForwardFactor(i)].variableIndices(&v[0]);
takes whatever type is given to variableIndices()
and on line line 552, 554, 557, 559 
v[0|1] is compared to varIndex() which returns a IndexType.

Moreover IndexType seems much more logical as v represents a variable index.

I ran into problems with label types as I have much more variables then LabelType (int 16) can represent.

**Comment by joergkappes** [comment]
Thanks Reinhard,
I fixed it with commit 592a3d8b8711d7ac5dd3847ef5315b546351277a

**Comment by ReinhardHameeteman** [comment]
Thanks for fixing!

Reinhard
