### ISSUE TITLE
OpenGM error

### ISSUE THREAD

**Issue by dingfg** [opengm/opengm#489]
Unexpected Standard exception from MEX file.
What() is:OpenGM error:TRBP is not a valid value for argument: "algorithm". Possible are: ICM; BRUTEFORCE; BELIEFPROPAGATION; ASTAR; LAZYFLIPPER; GRAPHCUT; ALPHAEXPANSION; ALPHABETASWAP;

**Comment by joergkappes** [comment]
Read the error message. It say whats wrong.
