### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dingfg** [opengm/opengm#490]
gm = openGMModel;
temp = [2,2];
gm.addVariables(temp);
unaryFunction_1 = openGMExplicitFunction(2,[0.4,0.6]);
gm.addFunction(unaryFunction_1);
gm.addFactors(unaryFunction_1,0);
unaryFunction_2 = openGMExplicitFunction(2,[0.7,0.3]);
gm.addFunction(unaryFunction_2);
gm.addFactors(unaryFunction_2,1);
inferenceResults = opengm('m', gm, 'a', 'BELIEFPROPAGATION', 'p', 1,...
    'timeout',inf, 'maxIt', 20, 'bound', 0.000001,'gaplimit',0,'memlogging',1,'damping',0.0);

question:
the result of inferenceResults.states is [0,1],why??? why not [1,0] ???

**Comment by joergkappes** [comment]
because 0.4+0.3 < 0.6+0.7 
inference is done in the min-sum-semiring!
